version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: g-management-app
    ports:
      - "8080:8080"
    environment:
      DSN: gadmin:gpassword@tcp(mysql:3306)/gdb
    depends_on:
      - mysql
    # volumes:
    #   - .:/app
    # command: ["go", "run", "./cmd/main.go"]

  mysql:
    image: mysql:8
    container_name: g-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./internal/migrations:/docker-entrypoint-initdb.d # runs SQL files on first startup

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: g-management-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  mysql_data:
  es_data:
